# kaggle datasets download -d omkargurav/face-mask-dataset
data:
  source_url: "https://drive.google.com/drive/folders/1wQjmjO8P8EZvT6dcda5gcSg7GXSc62s_?usp=sharing"
  local_dir: DataSet
  data_file: data.zip
  unzip_data_dir: DataSet
  parent_data_dir: mask_data
  model_dir: save_models
  trained_model_file: trained_model.h5

params:
  img_shape: [224, 224,3]
  lr: 0.001
  loss: categorical_crossentropy
  metrics: ["accuracy"]
  validation_split: 0.2
  batch_size: 32
  seed: 42
  buffer_size: tf.
  epochs: 1
